---

- name: Get VPC id
  vpc_lookup:
    region: "{{ region }}"
    tags:
      Name: "{{ vpc_name }}" 
  register: vpc

- set_fact:
    vpc_id: "{{ vpc.vpc_ids[0] }}"

- name: Get subnet facts
  ec2_vpc_subnet_facts:
    filters:
      vpc-id: "{{ vpc_id }}"
  register: vpc_subnet_facts 

- set_fact:
    public_subnet_id: "{{ (vpc_subnet_facts.subnets | selectattr('tags.Name','equalto','staging_subnet_public') | first).id }}"

- set_fact:
    private_subnet_id: "{{ (vpc_subnet_facts.subnets | selectattr('tags.Name','equalto','staging_subnet_private')) }}"

- debug: msg="{{ vpc_subnet_facts.subnets }}"

- name: Create subnet groups
  rds_subnet_group:
    name: dbsg2
    state: present
    region: "{{ region }}"
    description: DB subnet group2
    subnets:
      - "{{ private_subnet_id }}" 
