---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars_files:
    - ../staging_vpc_info
  vars:  
    key: "{{ keypair }}" 
    instance_type: t2.micro
    image: "{{ ami_id }}" 
    prefix: staging
  tasks:  
    - name: Provision web instance
      ec2:
        region: "{{ region }}"  
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"  
        image: "{{ image }}"
        wait: yes    
        group: "{{ prefix }}_sg_web"
        instance_tags:
          Name: "{{ prefix }}_web"
          class: web
          environment: staging
        vpc_subnet_id: "{{ staging_subnet_public }}"
      register: ec2  

    - name: Associate new EIP for the instance    
      ec2_eip:
        region: "{{ region }}"
        instance_id: "{{ item.id }}"
        in_vpc: yes
      with_items: ec2.instances
