---
# vars:
#   instance_type: t2.micro
#   image: "{{ ami_id }}"
#   prefix: "{{ prefix }}"

- name: Get VPC id
  vpc_lookup:
    region: "{{ region }}"
    tags:
      Name: "{{ vpc_name }}" 
  register: vpc

- set_fact:
    vpc_id: "{{ vpc.vpc_ids[0] }}"

# - name: Fetch all subnets for VPC
#   local_action: shell aws ec2 describe-subnets --filter Name=vpc-id,Values="{{ vpc_id }}" | jq --raw-output '[.[][].SubnetId]'
#   register: vpc_subnets

# - name: lkjasdflkjasdf
#   debug: msg="{{ vpc_subnets }}"

- name: get subnet facts
  ec2_vpc_subnet_facts:
    filters:
      vpc-id: "{{ vpc_id }}"
  register: vpc_subnet_facts 

- set_fact:
    public_subnet_id: "{{ (vpc_subnet_facts.subnets | selectattr('tags.Name','equalto','staging_subnet_public') | first).id }}"

- name: Provision EC2 instance
  ec2:
    region: "{{ region }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ami_id }}"
    wait: yes
    instance_tags:
      Name: "{{ prefix }}_web"
      class: web
      environment: staging
    id: web_launch01
    vpc_subnet_id: "{{ public_subnet_id }}"

  